### ISSUE TITLE
Thanks! It worked, but there were some side effects

### ISSUE THREAD

**Issue by gamma05772** [zhaodice/proxmox-ve-anti-detecion#1]
It worked and Succeed, thanks!
but All other virtual machines that's disk are used for virio are not start，Do you have such a problem?

**Comment by zhaodice** [comment]
yes,"virtio" is banned by this project,because virtio device can be only used in Virtual Machine,so some software can detect your disk driver "virtio" or "qemu-agent" installed, if it is installed or existed, your virtual machine will be detected.

**Comment by zhaodice** [comment]
of course, you can PCI passthough whole disk into your VM to get full performance

**Comment by gamma05772** [comment]
Thank you very much for your reply
