### ISSUE TITLE
Detected in private RO game

### ISSUE THREAD

**Issue by AtkCore** [zhaodice/proxmox-ve-anti-detecion#2]
![RO_Detected](https://github.com/zhaodice/proxmox-ve-anti-detection/assets/76583757/3b9fca97-f7f6-424c-af3f-c639ea85533d)

Your patch zhaodice works very well.
I use to play this retro game on my private server.
But 4-5 days ago, it was already detected.
What additional settings should I set to avoid detection?

I'm using google translate for this text, sorry if this text confuses you.

Thank you again for making this patch. I used it on my old computer and played the game with my 2 younger brothers. It feels great that this old computer can be used together with my family back in the childhood together.

**Comment by zhaodice** [comment]
I don't know whether it detected the virtual machine information or simply banned your host information, you can do follows:

1. re-install the OS to test whether detected
2. re-complie the proxmox program deb file with different device information (ASUS, MAC, SERIAL...)

**Comment by zhaodice** [comment]
I tested it on my machine , it is true that it has been detected.

**Comment by zhaodice** [comment]
sorry, but I have tried my best, the anti-cheat may use unknow virtual enviroment dection technology(I changed the machine info but detcted ), and I will ask the open-source community in readme to help us, ( But don't hold onto too much hope

**Comment by zhaodice** [comment]
I have found the detection reason : RDTSC ATTACK.
this anti-cheat uses "RDTSC ATTACK" to detect CPU's counter time to recognize it has been in VM, patch the kernel maybe a only one solution

**Comment by zhaodice** [comment]
![1](https://github.com/zhaodice/proxmox-ve-anti-detection/assets/63996691/1bcae320-c043-4fe1-9045-fe8c355aa87e)
Resolved in https://github.com/zhaodice/proxmox-ve-anti-detection/releases/tag/release

**Comment by nhamhuynh79** [comment]
Hi, can it work virt-manager?, i need a gui.

**Comment by zhaodice** [comment]
> Hi, can it work virt-manager?, i need a gui.

I think it works, patching kernel is essential.
