### ISSUE TITLE
如何让N卡vGPU可以正常工作

### ISSUE THREAD

**Issue by New-GitHub** [zhaodice/proxmox-ve-anti-detecion#27]
显卡是Tesla P4，做了vGPU，虚拟机补丁后，设备管理器可以看到显卡及驱动均正常，但是在任务管理器看不到GPU，也无法打开英伟达显卡控制面板。求助。

**Comment by zhaodice** [comment]
都virtual GPU了就别想着过检测了，假的不会变成真的

**Comment by New-GitHub** [comment]
> 都虚拟GPU了就别想着过检测了，假的不会变成真的

多谢答复。

这个的初衷不是为了让GPU过检测，是宿主机qemu补丁后，虚拟机GRID驱动有几率安装不成功。不太清楚是那块导致的这些问题。

后来反复测试以下发现和qemu补丁没有任何关系，是其他操作导致的。

1. 可能出现43的情况
2. 可能无法安装，提示检测未通过。
3. 设备管理器可以看到显卡及驱动均正常，但是在任务管理器看不到GPU，也无法打开英伟达显卡控制面板。
4. 和3一致的情况，重启后会驱动会显示感叹号。
