### ISSUE TITLE
please update to pve-qemu-kvm: 8.0.2-4

### ISSUE THREAD

**Issue by gamma05772** [zhaodice/proxmox-ve-anti-detecion#5]
please update to pve-qemu-kvm: 8.0.2-4,thanks

**Comment by gamma05772** [comment]
commit 409db0cd7bdc833e4a09d39492b319426029aa92 is 8.0.2-3
could you tell us commit id of 8.0.2-4
any response will be highly appreciated

**Comment by zhaodice** [comment]
I think this version is very small,  you may try compile it , it could no error I guess

**Comment by gamma05772** [comment]
8.0.2-4 commit	d9cbfafeeb9a529184b7ab2a8564fd3a1489ce83
