### ISSUE TITLE
在   命运方舟  中被检测到 ace

### ISSUE THREAD

**Issue by suigv** [zhaodice/proxmox-ve-anti-detecion#6]
很高兴你使用中文 我在命运方舟游戏中 不可过检测 这是一款腾讯的wegame网游 使用AntiCheatExpert
它会检测到错误弹出提示 关闭游戏  
![1801007723](https://github.com/zhaodice/proxmox-ve-anti-detection/assets/36131729/29fb15ea-2090-4aa7-87cf-19722c1a05b2)
以下是配置文件
`args: -cpu host,rdtscp=off,hv_time,+kvm_pv_unhalt,+kvm_pv_eoi,hv_spinlocks=0x1fff,-hy>
balloon: 0
bios: ovmf
boot: order=hostpci1;ide2
cores: 8cpu: host,flags=+pcid
efidisk0: local-zfs:vm-100-disk-0,efitype=4m,pre-enrolled-keys=1,size=1M
hostpci0: 0000:05:00,pcie=1,x-vga=1
hostpci1: 0000:01:00,pcie=1
ide2: local:iso/Lostark.iso,media=cdrom,size=60581082K
localtime: 1
machine: pc-q35-8.0
memory: 8192
meta: creation-qemu=8.0.2,ctime=1693505938
net0: e1000=BC:30:7E:23:82:28,bridge=vmbr0
numa: 1
ostype: win11
smbios1: uuid=832328ff-c8f4-42ee-92df-7081628fc63c,manufacturer=QVNVUw==,product=VVgz>
sockets: 1
usb0: host=1bcf:08a0,usb3=1
usb1: host=1c4f:0084,usb3=1
usb2: host=048d:1234,usb3=1
vga: none
vmgenid: aee350c9-a89b-4e8d-b0cd-2e681099b5cf`
如果有可能希望您抽空看一下 非常感谢我会持续关注

**Comment by suigv** [comment]
抱歉使用github不熟练 以下是从新粘贴的配置文件
**args: -cpu host,rdtscp=off,hv_time,+kvm_pv_unhalt,+kvm_pv_eoi,hv_spinlocks=0x1fff,-hypervisor,hv_vapic,hv_time,hv_reset,hv_vpindex,hv_runtime,hv_stimer,hv-synic,hv_relaxed,+invtsc,kvm=off,hv_vendor_id=intel,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true -smbios type=0,version=UX305UA.201 -smbios type=2,manufacturer=Intel,version=2021.5,product='MiHoYoSuperX' -smbios type=3,manufacturer=MiHoYo -smbios type=17,manufacturer=MiHoYo,loc_pfx=DDR5,speed=4800,serial=114514,part=1145 -smbios type=4,manufacturer=Intel,max-speed=4800,current-speed=4800
balloon: 0
bios: ovmf
boot: order=hostpci1;ide2
cores: 8
cpu: host,flags=+pcid
efidisk0: local-zfs:vm-100-disk-0,efitype=4m,pre-enrolled-keys=1,size=1M
hostpci0: 0000:05:00,pcie=1,x-vga=1
hostpci1: 0000:01:00,pcie=1
ide2: local:iso/Lostark.iso,media=cdrom,size=60581082K
localtime: 1
machine: pc-q35-8.0
memory: 8192
meta: creation-qemu=8.0.2,ctime=1693505938
net0: e1000=BC:30:7E:23:82:28,bridge=vmbr0
numa: 1
ostype: win11
smbios1: uuid=832328ff-c8f4-42ee-92df-7081628fc63c,manufacturer=QVNVUw==,product=VVgzMDVVQQ==,version=MjAyMS4x,serial=MTI0NjY3,sku=MTM0NDY4,family=Ng==,base64=1
sockets: 1
usb0: host=1bcf:08a0,usb3=1
usb1: host=1c4f:0084,usb3=1
usb2: host=048d:1234,usb3=1
vga: none
vmgenid: aee350c9-a89b-4e8d-b0cd-2e681099b5cf**

**Comment by zhaodice** [comment]
这没办法啊，我也没过瓦那个什么兰特的ACE（但旧版ACE可以），怀疑它并不是检测到了什么，而是没有检测到了什么，qemu缺少温度传感器，风扇啊这些乱七八糟的，我不清楚qemu要咋模拟，你有什么办法欢迎提出。

**Comment by zhaodice** [comment]
ACE已知很可能用的是这个方法检测的
```
use those commands could DETECT THIS VM (Shows "No instance available") , and NO SOLOTION CURRENTLY(I Don't know how to simulate thoses infomation..).

---------------------------

wmic path Win32_Fan get *

wmic path Win32_CacheMemory get *

wmic path Win32_VoltageProbe get *

wmic path Win32_PerfFormattedData_Counters_ThermalZoneInformation get *

wmic path CIM_Memory get *

wmic path CIM_Sensor get *

wmic path CIM_NumericSensor get *

wmic path CIM_TemperatureSensor get *

wmic path CIM_VoltageSensor get *
```
把wmic过了大概率可以了（要求从硬件层面，而不是掩耳盗铃）

**Comment by suigv** [comment]
非常感谢 我将考虑使用你提供的VMWare
[https://github.com/zhaodice/qemu-anti-detection/issues/19#issuecomment-1637052644](url)
