### ISSUE TITLE
please update to pve-qemu-kvm: 8.0.2-6

### ISSUE THREAD

**Issue by Ninenite13** [zhaodice/proxmox-ve-anti-detecion#8]
current it 8.0.2-6 and deb stay 8.0.2-3 please update thanks

**Comment by zhaodice** [comment]
But this is my first year as a graduate student, and may not have enough time to update immediately.  >_<

**Comment by Ninenite13** [comment]
Congratulations on graduating

i think i'm got pve-qemu-kvm_8.0.2-6_amd64 with commit 6c5563e30bea889ffc38a03d6ac86866c50e6484

i'm trying to create vm and try this deb

**Comment by Ninenite13** [comment]
![image](https://github.com/zhaodice/proxmox-ve-anti-detection/assets/88196412/2e5e8e0c-01a2-457a-9ba9-664ab158c178)

i try this follow guide

and i add arg like this 

> args: -cpu host,+kvm_pv_unhalt,+kvm_pv_eoi,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_reset,hv_vpindex,hv_runtime,hv_relaxed,kvm=off,hv_vendor_id=intel,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,hypervisor=off -smbios type=0,version=UX305UA.201 -smbios type=1,manufacturer=ASUS,product=UX305UA,version=2021.1 -smbios type=2,manufacturer=Intel,version=2021.5,product='Intel i9-12900K' -smbios type=3,manufacturer=XBZJ -smbios type=17,manufacturer=KINGSTON,loc_pfx=DDR5,speed=4800,serial=114514,part=FF63 -smbios type=4,manufacturer=Intel,max-speed=4800,current-speed=4800
bios: ovmf
boot: order=sata0;ide2;net0
cores: 6
cpu: host
efidisk0: local-lvm:vm-100-disk-0,efitype=4m,pre-enrolled-keys=1,size=4M
hostpci0: 0000:01:00.0,mdev=nvidia-57
ide2: local:iso/WIN11.PRO.22H2.SUPERLITE_SE_COMPACT.U9.4._WPE__.iso,media=cdrom,size=3792928K
machine: pc-q35-8.0
memory: 8192
meta: creation-qemu=8.0.2,ctime=1696443754
name: win11
net0: rtl8139=AA:23:F9:EC:5E:6E,bridge=vmbr0,firewall=1
numa: 0
ostype: win11
sata0: local-lvm:vm-100-disk-1,discard=on,size=120G,ssd=1
sata1: local-lvm:vm-100-disk-2,backup=0,size=32G
smbios1: uuid=8453fafc-426d-4d09-9bc4-7a11cce03c39
sockets: 1
tpmstate0: local-lvm:vm-100-disk-3,size=4M,version=v2.0
vga: none
vmgenid: eacf30e7-4f23-45df-9442-e9e653713b29


is it ok ? @zhaodice 

thanks

**Comment by Ninenite13** [comment]
result still got trace 

![image](https://github.com/zhaodice/proxmox-ve-anti-detection/assets/88196412/ea600207-b708-45d6-9846-a5605093613f)

any advice ?

**Comment by bolstersfury** [comment]
> result still got trace
> 
> ![image](https://user-images.githubusercontent.com/88196412/272690551-ea600207-b708-45d6-9846-a5605093613f.png)
> 
> any advice ?
>
Set the Bus/Device number to 1 instead of 0.
Not sure about the Bochs, I built the deb from scratch and mine is showing "OK".

![2023-10-05 07 09 12 192 168 1 52 221a02552f8f](https://github.com/zhaodice/proxmox-ve-anti-detection/assets/90597448/273c98da-46a0-42d3-a7bd-1370ade55a4b)

**Comment by zhaodice** [comment]
> result still got trace
> 
> ![image](https://user-images.githubusercontent.com/88196412/272690551-ea600207-b708-45d6-9846-a5605093613f.png)
> 
> any advice ?

you can paste content from this register value.

**Comment by Ninenite13** [comment]
Thank you very much to both of you @zhaodice  @XiSiSiST
